server:
  port: 5001

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
#        server-addr: ${NACOS_HOST:pig-register}:${NACOS_PORT:8848}
        server-addr: ${NACOS_HOST:81.71.48.29}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: pig-dev
  config:
    import:
      - nacos:pig-application-@profiles.active@.yml
#      - nacos:${spring.application.name}-@profiles.active@.yml